import * as fs from "fs";
import * as path from "path";
import { GenerationResult } from "./orchestrator";

/**
 * Creates a full Anchor project directory from generated code.
 * Returns the path to the project directory.
 */
export function scaffoldProject(
  result: GenerationResult,
  outputDir?: string
): string {
  const defaultBase = process.env.RAILWAY_ENVIRONMENT
    ? "/tmp/promptforge-output"
    : path.join(process.cwd(), "output");
  const projectDir = outputDir || path.join(defaultBase, result.programName);

  // Create directory structure
  const dirs = [
    projectDir,
    path.join(projectDir, "programs", result.programName, "src"),
    path.join(projectDir, "tests"),
    path.join(projectDir, "app"),
  ];

  for (const dir of dirs) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Write Anchor.toml
  const anchorToml = `[features]
seeds = false
skip-lint = false

[programs.devnet]
${result.programName} = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
`;
  fs.writeFileSync(path.join(projectDir, "Anchor.toml"), anchorToml);

  // Write Cargo.toml (workspace)
  const workspaceCargo = `[workspace]
members = [
    "programs/${result.programName}"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
`;
  fs.writeFileSync(path.join(projectDir, "Cargo.toml"), workspaceCargo);

  // Write program Cargo.toml
  const programCargo = `[package]
name = "${result.programName}"
version = "0.1.0"
description = "Generated by PromptForge"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "${result.programName.replace(/-/g, "_")}"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
`;
  fs.writeFileSync(
    path.join(projectDir, "programs", result.programName, "Cargo.toml"),
    programCargo
  );

  // Write the generated lib.rs
  fs.writeFileSync(
    path.join(projectDir, "programs", result.programName, "src", "lib.rs"),
    result.anchorCode
  );

  // Write Xargo.toml
  fs.writeFileSync(
    path.join(projectDir, "programs", result.programName, "Xargo.toml"),
    `[target.bpfel-unknown-unknown.dependencies.std]\nfeatures = []\n`
  );

  // Write a basic test file
  const testFile = `import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { assert } from "chai";

describe("${result.programName}", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  it("Program deployed successfully", async () => {
    // Basic deployment test
    console.log("Program ID:", "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");
    assert.ok(true, "Program exists");
  });
});
`;
  fs.writeFileSync(
    path.join(projectDir, "tests", `${result.programName}.ts`),
    testFile
  );

  // Write tsconfig.json for tests
  const tsconfig = `{
  "compilerOptions": {
    "types": ["mocha", "chai"],
    "typeRoots": ["./node_modules/@types"],
    "lib": ["es2015"],
    "module": "commonjs",
    "target": "es6",
    "esModuleInterop": true
  }
}
`;
  fs.writeFileSync(path.join(projectDir, "tsconfig.json"), tsconfig);

  return projectDir;
}
